[package]
authors = ["Charlie Chaplin"]
name = "forbids_unsafe"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_deps = { version = "0.1.0", path = "../simple_deps" }