[package]
authors = ["Emil Jonathan Eriksson <eje1999@gmail.com>"]
name = "indicate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
ron = "0.8.0"
trustfall_core = { git = "https://github.com/ginger51011/trustfall" }
serde = { version = "^1.0", features = ["derive"] }
cargo_metadata = "0.15.3"
cargo-index = "0.2.6"

[dev-dependencies]
regex = "1.7.1"
