[package]
authors = ["Charlie Chaplin"]
name = "dev_deps"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.107"

[dev-dependencies]
libc = "0.2.139"
