[package]
authors = ["Charlie Chaplin"]
name = "known_advisory_deps"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi_stable = "0.11.1"
sha2 = "0.10.6"